### ISSUE TITLE
Error when enabling module.

### ISSUE THREAD

**Issue by supermoos** [integratedexperts/jsonapi_embed#3]
When enabling this module, my endpoints that have Paragraphs fields on their content type fails:

`Error: Call to undefined method Drupal\jsonapi\Normalizer\ContentEntityNormalizer::isRelationship() in Drupal\jsonapi_embed\Normalizer\EmbedContentEntityNormalizer->isRelationship() (line 124 of /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/modules/jsonapi_embed-8.x-1.x/src/Normalizer/EmbedContentEntityNormalizer.php) #0 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/modules/jsonapi_embed-8.x-1.x/src/Normalizer/EmbedContentEntityNormalizer.php(91): Drupal\jsonapi_embed\Normalizer\EmbedContentEntityNormalizer->isRelationship(Object(Drupal\Core\Field\FieldItemList)) #1 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/modules/jsonapi_embed-8.x-1.x/src/Normalizer/EmbedContentEntityNormalizer.php(47): Drupal\jsonapi_embed\Normalizer\EmbedContentEntityNormalizer->serializeField(Object(Drupal\Core\Field\FieldItemList), Array, 'api_json') #2 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/vendor/symfony/serializer/Serializer.php(143): Drupal\jsonapi_embed\Normalizer\EmbedContentEntityNormalizer->normalize(Object(Drupal\node\Entity\Node), 'api_json', Array) #3 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/modules/jsonapi/src/Serializer/Serializer.php(46): Symfony\Component\Serializer\Serializer->normalize(Object(Drupal\node\Entity\Node), 'api_json', Array) #4 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/modules/jsonapi/src/Normalizer/JsonApiDocumentTopLevelNormalizer.php(228): Drupal\jsonapi\Serializer\Serializer->normalize(Object(Drupal\node\Entity\Node), 'api_json', Array) #5 [internal function]: Drupal\jsonapi\Normalizer\JsonApiDocumentTopLevelNormalizer->Drupal\jsonapi\Normalizer\{closure}(Object(Drupal\node\Entity\Node)) #6 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/modules/jsonapi/src/Normalizer/JsonApiDocumentTopLevelNormalizer.php(229): array_map(Object(Closure), Array) #7 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/modules/jsonapi/src/Normalizer/JsonApiDocumentTopLevelNormalizer.php(182): Drupal\jsonapi\Normalizer\JsonApiDocumentTopLevelNormalizer->buildNormalizerValue(Object(Drupal\node\Entity\Node), 'api_json', Array) #8 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/vendor/symfony/serializer/Serializer.php(143): Drupal\jsonapi\Normalizer\JsonApiDocumentTopLevelNormalizer->normalize(Object(Drupal\jsonapi\Resource\JsonApiDocumentTopLevel), 'api_json', Array) #9 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/modules/jsonapi/src/Serializer/Serializer.php(46): Symfony\Component\Serializer\Serializer->normalize(Object(Drupal\jsonapi\Resource\JsonApiDocumentTopLevel), 'api_json', Array) #10 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/vendor/symfony/serializer/Serializer.php(116): Drupal\jsonapi\Serializer\Serializer->normalize(Object(Drupal\jsonapi\Resource\JsonApiDocumentTopLevel), 'api_json', Array) #11 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/modules/jsonapi/src/EventSubscriber/ResourceResponseSubscriber.php(230): Symfony\Component\Serializer\Serializer->serialize(Object(Drupal\jsonapi\Resource\JsonApiDocumentTopLevel), 'api_json', Array) #12 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\jsonapi\EventSubscriber\ResourceResponseSubscriber->Drupal\jsonapi\EventSubscriber\{closure}() #13 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/modules/jsonapi/src/EventSubscriber/ResourceResponseSubscriber.php(233): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #14 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/modules/jsonapi/src/EventSubscriber/ResourceResponseSubscriber.php(169): Drupal\jsonapi\EventSubscriber\ResourceResponseSubscriber->renderResponseBody(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\jsonapi\ResourceResponse), Object(Drupal\jsonapi\Serializer\Serializer), 'api_json') #15 [internal function]: Drupal\jsonapi\EventSubscriber\ResourceResponseSubscriber->onResponse(Object(Symfony\Component\HttpKernel\Event\FilterResponseEvent), 'kernel.response', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #16 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\FilterResponseEvent), 'kernel.response', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #17 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/vendor/symfony/http-kernel/HttpKernel.php(191): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.response', Object(Symfony\Component\HttpKernel\Event\FilterResponseEvent)) #18 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/vendor/symfony/http-kernel/HttpKernel.php(173): Symfony\Component\HttpKernel\HttpKernel->filterResponse(Object(Drupal\jsonapi\ResourceResponse), Object(Symfony\Component\HttpFoundation\Request), 1) #19 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #20 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(184): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(121): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(75): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true) #25 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/modules/jsonapi/src/StackMiddleware/FormatSetter.php(40): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #26 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\jsonapi\StackMiddleware\FormatSetter->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #27 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(50): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #28 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #29 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/core/lib/Drupal/Core/DrupalKernel.php(664): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #30 /srv/bindings/36c10a7631834505a6ffdfc715253e19/code/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #31 {main}.`

**Comment by guix77** [comment]
That's because isRelationship() was removed from EntityNormalizer, which ContentEntityNormalizer extends, in jsonapi module in march : http://cgit.drupalcode.org/jsonapi/commit/src/Normalizer/EntityNormalizer.php?id=4a6f14f451bc10b098e1ccd7024f4d9ec3b80dca

In other words, jsonapi_embed is outdated.
